### ISSUE TITLE
Fails if only one post in RSS feed

### ISSUE THREAD

**Issue by dmpiq** [bbClassic/YRSS#1]
While testing, I had a feed with only one item in it.  YRSS would not display the contents.

As soon as I added a second post to the feed, it worked.

**Comment by markhillard** [comment]
Hmmmm, that is interesting. Are there any errors displayed in console if there is only one item in it?

**Comment by markhillard** [comment]
I tested this using the `limit: 1` option for a few feeds and I'm consistently receiving `undefined` in the HTML display. For some reason it builds out 6 entry wrappers when the limit is set to 1:

``` html
<div class="entryWrapper">...</div>
<div class="entryWrapper">...</div>
<div class="entryWrapper">...</div>
<div class="entryWrapper">...</div>
<div class="entryWrapper">...</div>
<div class="entryWrapper">...</div>
```

Working on it...

**Comment by markhillard** [comment]
After further testing, if an RSS feed only has one entry, the script still fails. There's nothing wrong with the data: https://developer.yahoo.com/yql/console/#h=select+*+from+feed+where+url%3D%22https%3A%2F%2Fbbis5740pssandbox.blackbaudhosting.com%2Ffeed.rss%3Fid%3D1%22+limit+1

The URL above is grabbing https://bbis5740pssandbox.blackbaudhosting.com/feed.rss?id=1 and there are no issues in the YQL Console.

If it's not YQL, then it must be an issue with the plugin.

**Comment by markhillard** [comment]
It's technically not an "issue" with the plugin, but it has to do with how jQuery's `$.each()` function works when it loops through a data set.

If there's only 1 entry in the set (set by the `limit` option or otherwise), the function doesn't build out an array with objects inside of it. Instead, it keeps the entry as a single object and iterates through its **properties**. There were 6 of them in my previous test and this was the reason why it was displaying 6 entry wrappers with `undefined` :bulb:

If you have more than 1 entry in the set, the function will build out each entry as an object inside an array, which allows you to grab specific information for each entry in the set using dot notation.

Here's what I'll be adding:

``` js
// check if entries are not inside an array (only 1 entry)
if (!$.isArray(entries)) { entries = [entries]; }
```

I've tested the plugin with multiple feeds using this code and I can't find any holes in it, so I'll push an update in the next few minutes.

@dmpiq, thanks very much for reporting this issue. YRSS is much better now!
